### ISSUE TITLE
Proxy errors 

### ISSUE THREAD

**Issue by painterzeou** [MrTimonM/dawn-validator-bot#2]
Proxy check failed: Missing dependencies
 for SOCKS support.

**Comment by painterzeou** [comment]
The solution was install PySocks
pip install PySocks


But had another faile.

 Failed to retrieve points.
 Keep alive failed on attempt 1. Response Code: 200

**Comment by painterzeou** [comment]
So the other error coz of token expired


What if you use email and pass instead of token
You'll just need orc for the captcha

**Comment by painterzeou** [comment]
The failure back again
Don't know what's the matter

Failed to retrieve points.
Keep alive failed on attempt 1. Response Code: 200

**Comment by MrTimonM** [comment]
> The failure back again Don't know what's the matter
> 
> Failed to retrieve points. Keep alive failed on attempt 1. Response Code: 200 | Keep alive failed on attempt 2. Response Code: 502 Bad Gatwway

Bad Gateway is their server error. You get this naturally in the extension too. 
This is not a serious issue.

**Comment by MrTimonM** [comment]
> So the other error coz of token expired
> 
> What if you use email and pass instead of token You'll just need orc for the captcha

I dont know how long token lasts, I am running since last 24 hours, Let's see.
Yes you can use captcha solver. There's other similar scripts in github with captcha solver included.
I will update this script gradually.
